### ISSUE TITLE
How to invite someone to join the Slack

### ISSUE THREAD

**Issue by kacollins** [techlahoma/slack-guide#1]
If this is someone you know and you have their email address:
* Click your workspace name in the sidebar.
* Select Invite people to... from the menu. 
* Enter the email address for anyone you'd like to invite. 
* Click Send, then click Done.

If this is someone you know but you don't have their email address:
* Click your workspace name in the sidebar.
* Select Invite people to... from the menu.
* Click Copy invite link. 

If you don't know someone, send them to [slack.techlahoma.org](http://slack.techlahoma.org/) where they can click to get their own link, by creating an account.

**Comment by er-lo** [comment]
I'd like to tackle this. Is there a style or template you'd want to be used?

**Comment by kacollins** [comment]
I think the decision has actually been made to not go forward with this repo. Thanks for offering though!
